namespace NetSamples.Tasks;

public class ParallelSample
{
    public void Do()
    {
        Parallel.Invoke(
            () => DoSmth(),
            DoSmth,
            () => Console.WriteLine("Help"));
    }


    public void DoFor()
    {
        Parallel.For(0, 100, Pow2);
    }

    public void DoForEach()
    {
        var totalPrice = 0;
        var listOfProduct = new List<Product>()
        {
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
        };

        var result = Parallel.ForEach(listOfProduct, 
            (product, state) => CalculateProductPrice(product, state));
        while (!result.IsCompleted)
        {
        }
        
    }

    private int CalculateProductPrice(Product product, ParallelLoopState state)
    {
        if (product.Price==10)
        {
            state.Break();
        }
        
        var task1 = new Task(() => CheckProductIsExist(product));
        var task2 = task1.ContinueWith(t => CheckProductPrice(product));
        var task3 = task2.ContinueWith(t => AddProductToCart(product));
        task1.Start();
        return task3.Result;
    }

    private void DoSmth()
    {
        Console.WriteLine("Smth");
    }

    private void Pow2(int n) => Console.WriteLine(n * n);
    private void CheckProductIsExist(Product product) => Console.WriteLine($"{product.Name} is exist");
    private void CheckProductPrice(Product product) => Console.WriteLine($"{product.Name}-${product.Price}");
    private int AddProductToCart(Product product)
    {
        Console.WriteLine($"{product.Name} was added to cart");
        return product.Price;
    }
}