namespace NetSamples.Tasks;

public class TaskSamples
{
    public void Do()
    {
        var outerTask = new Task(() =>
        {
            Console.WriteLine("Outer task started");
            var innerTask = new Task(() =>
            {
                Console.WriteLine("Inner task started"); 
                Thread.Sleep(2000);
                Console.WriteLine("Inner task ended");
            }, TaskCreationOptions.AttachedToParent);
            innerTask.Start();
            Console.WriteLine("Outer task ended");
        });

        outerTask.Start();
        outerTask.Wait();
        Console.WriteLine("End of Do");
    }

    public void RunFewTasksInParallel()
    {
        var listOfTasks = new List<Task>()
        {
            new Task(() => Console.WriteLine("First")),
            new Task(() => Console.WriteLine("Second")),
            new Task(() => Console.WriteLine("Third"))
        };

        foreach (var task in listOfTasks)
        {
            task.Start();
        }

        //Task.WaitAny(listOfTasks.ToArray());
        Task.WaitAll(listOfTasks.ToArray());
    }

    public void Calculate()
    {
        var numbers = new List<int>(){1,2,3,4,5,6};

       
        var listOfTasks = new List<Task<int>>();

        foreach (var number in numbers)
        {
            foreach (var secNumber in numbers)
            {
                var multiplyTask = new Task<int>(() => Multiply(number, secNumber));
                listOfTasks.Add(multiplyTask);
            }
        }

        foreach (var listOfTask in listOfTasks)
        {
            listOfTask.Start();
        }

        Task.WaitAll(listOfTasks.ToArray());

        var listOfResults = listOfTasks.Select(task => task.Result).ToList();
    }

    private int Multiply(int x, int y) => x * y;


    public void BuySmthSync()
    {
        var totalPrice = 0;
        var listOfProduct = new List<Product>()
        {
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
        };
        foreach (var product in listOfProduct)
        {
            CheckProductIsExist(product);
            CheckProductPrice(product);
            totalPrice += AddProductToCart(product);
        }
    }

    public void BuySmthInParallel()
    {
        var totalPrice = 0;
        var listOfProduct = new List<Product>()
        {
            new Product() { Name = "A", Price = 10 },
            new Product() { Name = "B", Price = 11 },
            new Product() { Name = "C", Price = 12 },
            new Product() { Name = "D", Price = 13 },
            new Product() { Name = "E", Price = 14 },
            new Product() { Name = "F", Price = 15 },
            new Product() { Name = "G", Price = 16 },
            new Product() { Name = "H", Price = 17 },
            new Product() { Name = "I", Price = 18 },
            new Product() { Name = "J", Price = 19 },
            new Product() { Name = "K", Price = 20 },
        };
        foreach (var product in listOfProduct)
        {
            var task1 = new Task(()=>CheckProductIsExist(product));
            var task2 = task1.ContinueWith(t=> CheckProductPrice(product));
            var task3 = task2.ContinueWith(t=>AddProductToCart(product));
            task1.Start();
            totalPrice += task3.Result;
        }
    }

    private void CheckProductIsExist(Product product) => Console.WriteLine($"{product.Name} is exist");
    private void CheckProductPrice(Product product) => Console.WriteLine($"{product.Name}-${product.Price}");
    private int AddProductToCart(Product product)
    {
        Console.WriteLine($"{product.Name} was added to cart");
        return product.Price;
    }

}